#!/bin/sh
export LC_CTYPE=ja_JP.SJIS
#/home/deuce/java/diablo-jdk1.5.0_06/bin/java -jar QDBUtil.jar
/usr/local/jdk1.4.2/bin/java -jar QDBUtil.jar >log.log 2>&1
#/usr/local/linux-sun-jdk1.6.0/bin/java -Dfile.encoding=sjis -jar QDBUtil.jar >log.log 2>&1
